# Generated by Django 4.0.5 on 2022-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_match_id',
            field=models.IntegerField(default=0),
        ),
    ]
