# Generated by Django 4.0.5 on 2022-06-17 12:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useruser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='useruser',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='date birth'),
        ),
        migrations.AlterField(
            model_name='useruser',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
