# Generated by Django 4.0.5 on 2022-06-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useruser_managers_alter_useruser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useruser',
            managers=[
            ],
        ),
    ]
